const API_URL=window.DIROX_API_URL||'';
const state={user:JSON.parse(localStorage.getItem('dirox.user')||'null'),projects:JSON.parse(localStorage.getItem('dirox.projects')||'[]'),active:null,skill:'Code agent'};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const authHeaders=()=>state.user?.access_token?{Authorization:`Bearer ${state.user.access_token}`,'Content-Type':'application/json'}:{'Content-Type':'application/json'};
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function show(id){['authView','dashboardView','workspaceView'].forEach(x=>$('#'+x).hidden=x!==id);document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===id))}
function save(){localStorage.setItem('dirox.projects',JSON.stringify(state.projects));if(state.user)localStorage.setItem('dirox.user',JSON.stringify(state.user))}
async function syncProjects(){if(!API_URL||!state.user?.access_token)return;try{const r=await fetch(API_URL+'/projects',{headers:authHeaders()});if(r.ok){state.projects=await r.json();save();render()}}catch{} }
function render(){if(!state.user){show('authView');return}$('#userName').textContent=state.user.name||state.user.email.split('@')[0];$('#projectCount').textContent=state.projects.length;$('#projectList').innerHTML=state.projects.length?state.projects.map((p,i)=>`<button class="project" data-project="${i}"><span class="project-icon">${i%2?'◈':'⌘'}</span><span><b>${esc(p.name)}</b><p>${esc(p.brief||'DiroX workspace')} · ${p.files?.length||3} files</p></span><time>now</time></button>`).join(''):'<div class="empty muted">No projects yet. Create your first workspace.</div>';show('dashboardView');document.querySelectorAll('[data-project]').forEach(x=>x.onclick=()=>openWorkspace(+x.dataset.project))}
function openWorkspace(i){state.active=i;const p=state.projects[i];$('#workspaceTitle').textContent=p.name;$('#fileList').innerHTML=(p.files||['index.html','style.css','app.js']).map((f,j)=>`<div class="file ${j===0?'active':''}">▱ ${esc(f)}<small>${j?'1.4 KB':'3.8 KB'} · now</small></div>`).join('');$('#chatMessages').innerHTML=`<div class="message agent"><div class="message-icon">✦</div><div><b>DiroX agent</b><p>“${esc(p.name)}” workspace is ready. <b>${esc(state.skill)}</b> selected. Write your task.</p></div></div>`;show('workspaceView')}
function openAuth(mode='login'){const d=$('#authDialog');d.showModal();$('#authForm').dataset.mode=mode;const signup=mode==='signup';$('#authTitle').textContent=signup?'Create your account':'Sign in to DiroX';$('#authName').hidden=!signup;$('#authSubmit').textContent=signup?'Create account':'Sign in';$('#authSwitch').textContent=signup?'Already have an account? Sign in':'No account? Create one'}
async function submitAuth(e){e.preventDefault();const mode=$('#authForm').dataset.mode,email=$('#authEmail').value.trim(),password=$('#authPassword').value;try{if(API_URL){const r=await fetch(API_URL+'/auth/'+mode,{method:'POST',headers:authHeaders(),body:JSON.stringify({email,password,name:$('#authName').value})});const d=await r.json();if(!r.ok)throw Error(d.error||'Authentication failed');state.user={...d,email};}else state.user={email,name:$('#authName').value||email.split('@')[0]};save();$('#authDialog').close();render();syncProjects();toast('Welcome!')}catch(err){$('#authError').textContent=err.message}}
async function sendMessage(text){const box=$('#chatMessages');box.insertAdjacentHTML('beforeend',`<div class="message user"><div>${esc(text)}</div></div>`);$('#chatInput').value='';const waiting=document.createElement('div');waiting.className='message agent';waiting.innerHTML='<div class="message-icon">✦</div><div><b>DiroX agent</b><p>Analyzing your task…</p></div>';box.append(waiting);try{if(!API_URL)throw Error('demo');const r=await fetch(API_URL+'/chat',{method:'POST',headers:authHeaders(),body:JSON.stringify({message:text,skill:state.skill,project:state.projects[state.active]})});const d=await r.json();if(!r.ok)throw Error(d.error||'AI request failed');waiting.querySelector('p').textContent=d.reply}catch(err){waiting.querySelector('p').textContent=err.message==='demo'?'Demo mode: connect your Railway API using DIROX_API_URL.':'Could not connect to the AI service.'}box.scrollTop=box.scrollHeight}
$('#authForm').onsubmit=submitAuth;$('#authSwitch').onclick=()=>openAuth($('#authForm').dataset.mode==='login'?'signup':'login');document.querySelectorAll('[data-open-auth]').forEach(x=>x.onclick=()=>openAuth());document.querySelector('[data-close-auth]').onclick=()=>$('#authDialog').close();$('#newProject').onclick=()=>$('#projectDialog').showModal();$('#projectForm').onsubmit=async e=>{e.preventDefault();const p={name:$('#projectName').value.trim(),brief:$('#projectBrief').value.trim(),files:['index.html','style.css','app.js']};if(API_URL&&state.user?.access_token){const r=await fetch(API_URL+'/projects',{method:'POST',headers:authHeaders(),body:JSON.stringify(p)});if(r.ok)state.projects.unshift((await r.json())[0]||p);else toast('Could not create project')}else state.projects.push(p);save();$('#projectDialog').close();e.target.reset();render();toast('Workspace created')};document.querySelector('[data-close-project]').onclick=()=>$('#projectDialog').close();$('#backDashboard').onclick=render;$('#chatForm').onsubmit=e=>{e.preventDefault();const t=$('#chatInput').value.trim();if(t)sendMessage(t)};document.querySelectorAll('[data-prompt]').forEach(x=>x.onclick=()=>sendMessage(x.dataset.prompt));$('#skillButton').onclick=()=>{const skills=['Code agent','Planning agent','Design agent','Files agent','Publishing agent'];state.skill=skills[(skills.indexOf(state.skill)+1)%skills.length];$('#skillButton').innerHTML='⌘ '+state.skill+' <span>⌄</span>';toast(state.skill+' selected')};document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>x.dataset.nav==='workspaceView'&&state.projects.length?openWorkspace(0):x.dataset.nav==='dashboardView'?render():toast(state.projects.length?'Select a project first':'Sign in first'));$('#accountBtn').onclick=()=>state.user?(state.user=null,localStorage.removeItem('dirox.user'),render(),toast('Signed out')):openAuth();$('#menuBtn').onclick=()=>toast('DiroX menu');$('#skillsNav').onclick=()=>toast('Skills: Code · Planning · Design · Files · Publishing');$('#settingsNav').onclick=()=>toast('Settings are managed through the Railway backend');render();syncProjects();