import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildRepoMap } from './context/repo-map.js';
import { retrieveContext } from './context/retrieval.js';
import { createMemory, summarizeMemory } from './context/memory.js';
import { runAgentLoop } from './agent/loop.js';

const PORT=process.env.PORT||3000;
const ROOT=join(fileURLToPath(new URL('.',import.meta.url)),'..');
const OPENROUTER_URL='https://openrouter.ai/api/v1/chat/completions';
const SUPABASE_URL=process.env.SUPABASE_URL||'';
const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||'';
const json=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))};
const read=async req=>{let b='';for await(const c of req)b+=c;try{return JSON.parse(b||'{}')}catch{return {}}};
const sb=async(path,options={})=>fetch(`${SUPABASE_URL}${path}`,{...options,headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json',...(options.headers||{})}});
const token=req=>req.headers.authorization?.replace(/^Bearer\s+/,'')||'';
async function userFrom(req){const t=token(req);if(!t||!SUPABASE_URL)return null;const r=await sb('/auth/v1/user',{headers:{Authorization:`Bearer ${t}`}});return r.ok?await r.json():null}
async function adminFrom(req){const u=await userFrom(req);if(!u)return null;const r=await sb(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(u.id)}&select=user_id&limit=1`,{headers:{Authorization:`Bearer ${token(req)}`}});if(!r.ok)return null;const rows=await r.json();return rows?.length?u:null}
async function adminSettings(req){const r=await sb('/rest/v1/admin_settings?select=key,value',{headers:{Authorization:`Bearer ${token(req)}`}});if(!r.ok)return {};const rows=await r.json();return Object.fromEntries((rows||[]).map(x=>[x.key,x.value]))}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'};
async function staticFile(req,res){const requested=req.url==='/'?'/index.html':req.url.split('?')[0];const file=normalize(join(ROOT,requested));if(!file.startsWith(ROOT)||requested.includes('..'))return false;try{const data=await readFile(file);res.statusCode=200;res.setHeader('Content-Type',types[extname(file)]||'application/octet-stream');res.end(data);return true}catch{return false}}
const server=createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin',process.env.FRONTEND_URL||'*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.end();
 if(req.method==='GET'&&(req.url==='/'||req.url.startsWith('/index.html')||req.url.startsWith('/style.css')||req.url.startsWith('/app.js')||req.url.startsWith('/assets/'))){if(await staticFile(req,res))return}
 if(req.url==='/health')return json(res,200,{ok:true,service:'DiroX'});
 if((req.url==='/auth/login'||req.url==='/auth/signup')&&req.method==='POST'){if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return json(res,503,{error:'Supabase environment is not configured'});const body=await read(req);const signup=req.url.endsWith('signup');const target=signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const payload=signup?{email:body.email,password:body.password,data:{full_name:body.name||''}}:{email:body.email,password:body.password};try{const r=await sb(target,{method:'POST',body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return json(res,r.status,{error:d.error_description||d.msg||d.message||'Authentication failed'});return json(res,200,{...d,name:body.name||d.user?.user_metadata?.full_name||d.user?.email?.split('@')[0]})}catch{return json(res,502,{error:'Could not connect to Supabase'})}}
 if(req.url==='/projects'&&req.method==='GET'){const u=await userFrom(req);if(!u)return json(res,401,{error:'Authentication required'});const r=await sb(`/rest/v1/projects?user_id=eq.${encodeURIComponent(u.id)}&select=*&order=created_at.desc`,{headers:{Authorization:`Bearer ${token(req)}`}});return json(res,r.status,await r.json())}
 if(req.url==='/projects'&&req.method==='POST'){const u=await userFrom(req);if(!u)return json(res,401,{error:'Authentication required'});const body=await read(req);if(!body.name)return json(res,400,{error:'Project name is required'});const r=await sb('/rest/v1/projects',{method:'POST',headers:{Authorization:`Bearer ${token(req)}`,'Prefer':'return=representation'},body:JSON.stringify({user_id:u.id,name:String(body.name).slice(0,120),brief:String(body.brief||'').slice(0,1000),files:body.files||['index.html','style.css','app.js']})});return json(res,r.status,await r.json())}
 if(req.url==='/admin/me'&&req.method==='GET'){const u=await adminFrom(req);return json(res,200,{admin:!!u,name:u?.user_metadata?.full_name||u?.email?.split('@')[0]||''})}
 if(req.url==='/admin/settings'&&req.method==='GET'){if(!await adminFrom(req))return json(res,403,{error:'Admin access required'});const s=await adminSettings(req);return json(res,200,{models:{low:s.model_low||'openai/gpt-4o-mini',medium:s.model_medium||'openai/gpt-4o-mini',high:s.model_high||'openai/gpt-4o-mini'},defaultLanguage:s.default_language||'English'})}
 if(req.url==='/admin/settings'&&req.method==='PUT'){if(!await adminFrom(req))return json(res,403,{error:'Admin access required'});const body=await read(req);const values={model_low:String(body.models?.low||'').slice(0,160),model_medium:String(body.models?.medium||'').slice(0,160),model_high:String(body.models?.high||'').slice(0,160),default_language:String(body.defaultLanguage||'English').slice(0,40)};const r=await sb('/rest/v1/admin_settings',{method:'POST',headers:{Authorization:`Bearer ${token(req)}`,'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(Object.entries(values).map(([key,value])=>({key,value})))});return json(res,r.ok?200:r.status,r.ok?{ok:true}:{error:'Settings could not be saved'})}
 if(req.url==='/agent/run'&&req.method==='POST'){const u=await userFrom(req);if(!u)return json(res,401,{error:'Authentication required'});const body=await read(req);const task={title:String(body.title||body.message||'').slice(0,300),description:String(body.description||body.message||'').slice(0,10000)};if(!task.description)return json(res,400,{error:'Task is empty'});try{const repoMap=await buildRepoMap(ROOT);const context=await retrieveContext({rootDir:ROOT,repoMap,query:task.description,maxChars:Math.min(Number(body.contextBudget)||12000,20000),maxFiles:6});const memory=createMemory(body.memory);const settings=await adminSettings(req);const result=await runAgentLoop(task,{models:{OPENROUTER_MODEL_LOW:settings.model_low,OPENROUTER_MODEL_MEDIUM:settings.model_medium,OPENROUTER_MODEL_HIGH:settings.model_high,OPENROUTER_MODEL:settings.model_medium},context:{relevant:JSON.stringify({files:context.items,memory:summarizeMemory(memory,1800)})},planResponse:body.planResponse,evidenceFor:async execution=>execution.evidence||body.evidence||{}});if(body.projectId){await sb('/rest/v1/tasks',{method:'POST',headers:{Authorization:`Bearer ${token(req)}`,'Prefer':'return=minimal'},body:JSON.stringify({user_id:u.id,project_id:body.projectId,title:task.title,description:task.description,status:result.task.status,state:result.task})})}return json(res,200,{...result,context:{files:context.items.map(item=>({path:item.path,symbol:item.symbol,startLine:item.startLine,endLine:item.endLine})),chars:context.chars,truncated:context.truncated}})}catch(error){return json(res,502,{error:error?.message||'Agent loop failed'})}}
 if(req.url==='/chat'&&req.method==='POST'){const body=await read(req);if(!body.message)return json(res,400,{error:'Message is empty'});if(!process.env.OPENROUTER_API_KEY)return json(res,503,{error:'OPENROUTER_API_KEY is not configured'});const skill=String(body.skill||'Code agent');const system=`You are the ${skill} inside DiroX. Reply in the user's language unless they request another language. Keep responses concise and practical to save tokens. For big projects, give a short plan and one clear next step. Project context: ${JSON.stringify(body.project||{})}`;try{const r=await fetch(OPENROUTER_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':process.env.FRONTEND_URL||'https://dirox.app','X-Title':'DiroX'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||'openai/gpt-4o-mini',messages:[{role:'system',content:system},{role:'user',content:String(body.message).slice(0,12000)}],temperature:.2,max_tokens:900})});const d=await r.json();if(!r.ok)return json(res,r.status,{error:d?.error?.message||'OpenRouter request failed'});const reply=d?.choices?.[0]?.message?.content||'No answer returned.';const u=await userFrom(req);if(u&&body.project?.id)await sb('/rest/v1/chats',{method:'POST',headers:{Authorization:`Bearer ${token(req)}`},body:JSON.stringify({user_id:u.id,project_id:body.project.id,role:'user',content:String(body.message).slice(0,12000)})});return json(res,200,{reply})}catch{return json(res,502,{error:'Could not connect to the AI service'})}}
 json(res,404,{error:'Not found'});});
server.listen(PORT,()=>console.log(`DiroX API listening on ${PORT}`));