import { createServer } from 'node:http';
const PORT=process.env.PORT||3000;
const OPENROUTER_URL='https://openrouter.ai/api/v1/chat/completions';
const SUPABASE_URL=process.env.SUPABASE_URL||'';
const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||'';
const json=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))};
const read=async req=>{let b='';for await(const c of req)b+=c;try{return JSON.parse(b||'{}')}catch{return {}}};
const sb=async(path,options={})=>fetch(`${SUPABASE_URL}${path}`,{...options,headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json',...(options.headers||{})}});
const token=req=>req.headers.authorization?.replace(/^Bearer\s+/,'')||'';
async function userFrom(req){const t=token(req);if(!t||!SUPABASE_URL)return null;const r=await sb('/auth/v1/user',{headers:{Authorization:`Bearer ${t}`}});return r.ok?await r.json():null}
const server=createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin',process.env.FRONTEND_URL||'*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.end();
 if(req.url==='/health')return json(res,200,{ok:true,service:'DiroX'});
 if((req.url==='/auth/login'||req.url==='/auth/signup')&&req.method==='POST'){if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return json(res,503,{error:'Supabase environment is not configured'});const body=await read(req);const signup=req.url.endsWith('signup');const target=signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const payload=signup?{email:body.email,password:body.password,data:{full_name:body.name||''}}:{email:body.email,password:body.password};try{const r=await sb(target,{method:'POST',body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return json(res,r.status,{error:d.error_description||d.msg||d.message||'Authentication failed'});return json(res,200,{...d,name:body.name||d.user?.user_metadata?.full_name||d.user?.email?.split('@')[0]})}catch{return json(res,502,{error:'Could not connect to Supabase'})}}
 if(req.url==='/projects'&&req.method==='GET'){const u=await userFrom(req);if(!u)return json(res,401,{error:'Authentication required'});const r=await sb(`/rest/v1/projects?user_id=eq.${encodeURIComponent(u.id)}&select=*&order=created_at.desc`,{headers:{Authorization:`Bearer ${token(req)}`}});return json(res,r.status,await r.json())}
 if(req.url==='/projects'&&req.method==='POST'){const u=await userFrom(req);if(!u)return json(res,401,{error:'Authentication required'});const body=await read(req);if(!body.name)return json(res,400,{error:'Project name is required'});const r=await sb('/rest/v1/projects',{method:'POST',headers:{Authorization:`Bearer ${token(req)}`,'Prefer':'return=representation'},body:JSON.stringify({user_id:u.id,name:String(body.name).slice(0,120),brief:String(body.brief||'').slice(0,1000),files:body.files||['index.html','style.css','app.js']})});return json(res,r.status,await r.json())}
 if(req.url==='/chat'&&req.method==='POST'){const body=await read(req);if(!body.message)return json(res,400,{error:'Message is empty'});if(!process.env.OPENROUTER_API_KEY)return json(res,503,{error:'OPENROUTER_API_KEY is not configured'});const skill=String(body.skill||'Code agent');const system=`You are the ${skill} inside DiroX. Reply in English. Keep responses concise and practical to save tokens. For big projects, give a short plan and one clear next step. Project context: ${JSON.stringify(body.project||{})}`;try{const r=await fetch(OPENROUTER_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':process.env.FRONTEND_URL||'https://dirox.app','X-Title':'DiroX'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||'openai/gpt-4o-mini',messages:[{role:'system',content:system},{role:'user',content:String(body.message).slice(0,12000)}],temperature:.2,max_tokens:900})});const d=await r.json();if(!r.ok)return json(res,r.status,{error:d?.error?.message||'OpenRouter request failed'});const reply=d?.choices?.[0]?.message?.content||'No answer returned.';const u=await userFrom(req);if(u&&body.project?.id)await sb('/rest/v1/chats',{method:'POST',headers:{Authorization:`Bearer ${token(req)}`},body:JSON.stringify({user_id:u.id,project_id:body.project.id,role:'user',content:String(body.message).slice(0,12000)})});return json(res,200,{reply})}catch{return json(res,502,{error:'Could not connect to the AI service'})}}
 json(res,404,{error:'Not found'});});
server.listen(PORT,()=>console.log(`DiroX API listening on ${PORT}`));